In [1]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_excel('/home/ekim_reverse/study/Python.study/DATA_20191210_prep4.xlsx', sheet_name="filtered")

In [2]:
data_01 = pd.read_excel('/home/ekim_reverse/study/Python.study/DATA_20191210_prep4_1.xlsx', sheet_name="filtered")

In [7]:
data.head()

,RID,SEX,phase,AS1_GLU,AS2_GLU,AS3_GLU,AS4_GLU,AS5_GLU,AS6_GLU,AS7_GLU,...,AS6_HBA1C,AS7_HBA1C,AS1_HOMA,AS2_HOMA,AS3_HOMA,AS4_HOMA,AS5_HOMA,AS6_HOMA,AS7_HOMA,DM
0,EPI18_079_000033,1,4,104,113,121,140,109,105,114,...,5.9,6.0,1.335309,1.340000,1.830000,2.316049,1.399506,1.659259,2.082963,1
1,EPI18_079_000051,2,3,83,99,104,108,83,90,112,...,5.3,5.7,1.578025,1.980000,1.753086,4.080000,1.598519,1.866667,3.899259,1
2,EPI18_079_000069,1,2,82,138,100,91,96,111,118,...,5.6,5.9,2.247407,3.645926,2.469136,1.954815,1.991111,1.836296,2.097778,1
3,EPI18_079_000075,2,6,82,89,100,99,104,98,123,...,6.7,6.1,0.749136,3.823704,2.754321,3.568889,3.826173,2.758519,5.557778,1
4,EPI18_079_000126,2,4,89,103,115,132,123,126,136,...,6.7,7.1,1.186667,3.128148,0.792593,3.454815,2.551111,2.022222,2.720000,1

In [8]:
gluList = data.loc[:,"AS1_GLU":"AS7_GLU"]
altList = data.loc[:,"AS1_ALT":"AS7_ALT"]
tgList = data.loc[:,"AS1_TG":"AS7_TG"]
waistList = data.loc[:,"AS1_WAIST":"AS7_WAIST"]
fib4List = data.loc[:,"AS1_FIB4":"AS7_FIB4"]
hba1cList = data.loc[:,"AS1_HBA1C":"AS7_HBA1C"]
homaList = data.loc[:,"AS1_HOMA":"AS7_HOMA"]

In [9]:
gluList

      AS1_GLU  AS2_GLU  AS3_GLU  AS4_GLU  AS5_GLU  AS6_GLU  AS7_GLU
0         104      113      121      140      109      105      114
1          83       99      104      108       83       90      112
2          82      138      100       91       96      111      118
3          82       89      100       99      104       98      123
4          89      103      115      132      123      126      136
...       ...      ...      ...      ...      ...      ...      ...
2977       78       81      110       87       91       93       82
2978       86       91       87       95       92       88       93
2979       94       97       82       90       98       92       92
2980       89       88       80       87       89       97       90
2981       80       92       87       87       92       88       88

[2982 rows x 7 columns]

In [22]:
df=pd.DataFrame()

In [23]:
data["phase"][0]

4

In [24]:
gluList.columns = [1,2,3,4,5,6,7]
altList.columns = [1,2,3,4,5,6,7]
tgList.columns = [1,2,3,4,5,6,7]
waistList.columns = [1,2,3,4,5,6,7]
fib4List.columns = [1,2,3,4,5,6,7]
hba1cList.columns = [1,2,3,4,5,6,7]
homaList.columns = [1,2,3,4,5,6,7]

In [3]:
gluList_01 = data_01.loc[:,"AS1_GLU":"AS7_GLU"]
altList_01 = data_01.loc[:,"AS1_ALT":"AS7_ALT"]
tgList_01 = data_01.loc[:,"AS1_TG":"AS7_TG"]
waistList_01 = data_01.loc[:,"AS1_WAIST":"AS7_WAIST"]
fib4List_01 = data_01.loc[:,"AS1_FIB4":"AS7_FIB4"]
hba1cList_01 = data_01.loc[:,"AS1_HBA1C":"AS7_HBA1C"]
homaList_01 = data_01.loc[:,"AS1_HOMA":"AS7_HOMA"]

In [13]:
endData = []
for i in range(len(gluList)):
    for j in range(len(gluList.columns)):
        if data["phase"][i]==gluList.columns[j]:
            endData.append(gluList[j+1][i]-gluList[j][i])
df['glu_01'] = endData
print(df)

      glu_01
0         19
1          5
2         56
3         -6
4         17
...      ...
2977     -11
2978       5
2979       0
2980      -7
2981       0

[2982 rows x 1 columns]

In [4]:
altList_01

     AS1_ALT  AS2_ALT  AS3_ALT  AS4_ALT  AS5_ALT  AS6_ALT  AS7_ALT
0         83       56       63       32       26       54       89
1         16       13       17       13       14       15       13
2         30       33       31       16       14       18       24
3         15       24       20       27       38       21       45
4         19       24       26       24       21       18       20
..       ...      ...      ...      ...      ...      ...      ...
367       38       19       41       37       23       40       40
368       19       28       25       18       24       25       16
369       19       16       19       12       15       17       10
370       33       18       26       18       36       45       35
371       69       93       81       58       52       22       27

[372 rows x 7 columns]

In [5]:
gluList_01.columns = [1,2,3,4,5,6,7]
altList_01.columns = [1,2,3,4,5,6,7]
tgList_01.columns = [1,2,3,4,5,6,7]
waistList_01.columns = [1,2,3,4,5,6,7]
fib4List_01.columns = [1,2,3,4,5,6,7]
hba1cList_01.columns = [1,2,3,4,5,6,7]
homaList_01.columns = [1,2,3,4,5,6,7]

In [56]:
df_01=pd.DataFrame()

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==7:
        endData.append(homaList_01[7][i]-homaList_01[6][i])
        
df_01['homa_01'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==7:
        endData.append(homaList_01[7][i]-homaList_01[5][i])
        
df_01['homa_02'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==7:
        endData.append(homaList_01[7][i]-homaList_01[4][i])
        
df_01['homa_03'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==7:
        endData.append(homaList_01[7][i]-homaList_01[3][i])
        
df_01['homa_04'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==7:
        endData.append(homaList_01[7][i]-homaList_01[2][i])
        
df_01['homa_05'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==7:
        endData.append(homaList_01[7][i]-homaList_01[1][i])
        
df_01['homa_06'] = endData

print(df_01)

     homa_01    homa_02    homa_03    homa_04    homa_05    homa_06
0   0.047407  -0.020494  -1.089630   1.526420  -0.565432   0.131358
1  -0.570864  -1.299259  -0.179753  -0.167407   0.338025   0.746667
2   0.740741  -0.194568   0.014074  -1.282963   0.235309   0.220988
3   0.605432   0.143951   0.537778  -0.126420   0.678519   0.079012
4   0.146667  -1.063210  -0.099259  -0.897037  -0.635556   0.374074
5  -0.460494  -0.369383   0.131852  -0.506420   0.508395   1.514074
6   0.684938  -0.364198   0.263951   1.604444   1.583210   1.562469
7   0.474568   0.548642  -1.078025  -1.649136   1.090864  -0.062469
8  -0.455556  -0.201728   0.667901   0.636790   0.606790   0.609877
9  -0.578765   0.628395   0.524691  -0.648889   0.102222   0.000741
10  1.494815   1.771358   0.271358   2.936790   2.452840   1.409383
11  2.536296   2.183704   2.772840   2.947284   3.113580   3.341728
12 -0.302963  -0.354815  -3.427654   0.402963   0.726667   0.645185
13 -0.956543   1.851111   0.034321  -1.598025   1.180494   0.531358
14  3.454815   5.455309   4.512593   4.978519   6.148519   7.317037
15  2.558765   2.248889   2.049877   2.037531   1.483086   0.923210
16 -0.808889   0.283210  -1.480000  -0.133333  -1.026914   0.947654
17 -1.683951  -0.886914  -1.181728   0.500000   0.457778  -1.116049
18 -0.869630  -0.266173   0.976296   0.257037  -0.464691   0.185185
19  0.444198  -0.206173  -0.133580  -1.848148  -0.048148   1.756296
20  1.405432   1.309136   1.016543   1.100988   1.185432   1.841975
21 -0.017037  -0.833580  -0.364444  -2.451605  -0.326173   0.409630
22  2.334074   3.032840   3.016049   1.222222   3.519506   3.380494
23  0.984444   0.513333   1.439753  -0.250123   1.425926   0.718272
24  0.292593   1.753333   2.291605   3.864938   2.073333   3.757284
25  1.061728   0.657778   1.746667   1.145926   1.375926   1.608395
26  0.044444   0.539753  -1.552593   0.660741   0.287407  -0.089383
27  0.071358  -0.355802   0.243704   0.057531  -0.297037   1.041235
28  0.894321   0.644444   1.868148   0.361975   0.134815   0.675556
29  9.421975  12.384938  10.196049  14.124444  13.717037  13.699753
30  4.648395   6.784691   3.818765   6.459259   6.253333   4.614321
31  1.445926  -3.077531   1.099259   0.955062   2.602963   2.157037
32  0.935802   0.105185  -0.378765  -1.711358   0.229136   2.164444
33  0.573086   0.311358  -0.215062   0.582346   1.381235   2.093086
34 -1.782222  -0.458272  -2.788148   0.014815  -1.627160  -1.182222
35  2.817531   4.815802   5.400247   5.220000   6.044074   6.874074
36 -1.330864  -0.800247  -7.746420  -0.547407  -3.366667   0.443951
37  0.635556   1.734074   0.818765   2.546173   1.920000   3.125926
38  0.914321   0.207654   1.320000   0.428642  -0.147654   0.685432
39  0.513580   1.026914   1.966914  -0.021728   0.959136   1.942469
40  1.395062   1.866420   1.900247   3.016543   2.406173   3.031358
41  0.846914   0.732840   1.169383   2.919506   1.998025   1.941728
42  2.623704   2.888889  -1.311111   2.258025  -0.407901   2.038519
43  2.141481   2.117778   2.248889  -1.850864   2.371358   4.001481
44  1.476543   0.580247   2.381728   0.067654   1.867407   1.283951
45  0.248642  -1.917037  -0.720000  -1.000247  -0.751111  -0.414815
46 -0.172346  -0.768395  -2.483457  -0.029136   1.618272   0.646173
47  0.547654   0.084691   0.353333  -1.337037   0.202469   0.622222
48  0.122469   0.304938   0.108395  -3.253827  -1.558272  -0.093086
49  0.390123  -0.054321  -0.291605  -1.528889  -0.588025   0.360494
50  1.609136   1.762469   1.680494   4.623210   2.594568   1.517531
51 -0.162963   0.340000   0.468642  -1.107654   1.090370   2.279753
52  1.593086   2.482716   2.422716   2.461975   3.706914   3.520000
53  1.735802   1.203951   0.103704   2.065432   1.442099   0.823210
54  0.120988  -0.873580  -0.173333   1.340247   1.107407   0.872099
55 -0.386914   0.270864   0.100494   0.134321   0.664938   0.630617
56 -1.105185  -0.946667  -0.832593   0.180370   1.201481  -0.220741

In [57]:
df_02 = pd.DataFrame()
endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==6:
        endData.append(homaList_01[6][i]-homaList_01[5][i])
        
df_02['homa_01'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==6:
        endData.append(homaList_01[6][i]-homaList_01[4][i])
        
df_02['homa_02'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==6:
        endData.append(homaList_01[6][i]-homaList_01[3][i])
        
df_02['homa_03'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==6:
        endData.append(homaList_01[6][i]-homaList_01[2][i])
        
df_02['homa_04'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==6:
        endData.append(homaList_01[6][i]-homaList_01[1][i])
        
df_02['homa_05'] = endData

print(df_02)

     homa_01   homa_02   homa_03   homa_04   homa_05
0  -1.067654 -0.810370  0.004198 -1.065185  2.009383
1   1.408395  2.854321  1.976296  1.768889  3.883457
2  -1.061975  0.658519 -1.012099  0.043457 -0.048642
3   6.246667  6.540741  7.847901  7.864198  6.800988
4  -0.111605 -0.245432 -2.147654  0.345185  0.273333
..       ...       ...       ...       ...       ...
68  1.411111  0.611111 -0.340988  0.546667  1.439506
69  0.188642  0.831852  0.573827  0.945679  0.616790
70  1.690864  2.464198  2.617284  3.560494  3.207901
71 -0.257284  0.712840 -0.328642  1.910370  1.289136
72 -1.631605 -0.152099  0.197531  0.484568  0.764444

[73 rows x 5 columns]

In [58]:
df_03 = pd.DataFrame()
endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==5:
        endData.append(homaList_01[5][i]-homaList_01[4][i])
        
df_03['homa_01'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==5:
        endData.append(homaList_01[5][i]-homaList_01[3][i])
        
df_03['homa_02'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==5:
        endData.append(homaList_01[5][i]-homaList_01[2][i])
        
df_03['homa_03'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==5:
        endData.append(homaList_01[5][i]-homaList_01[1][i])
        
df_03['homa_04'] = endData

print(df_03)

     homa_01   homa_02   homa_03   homa_04
0  -0.235062  0.677531  1.598272  0.303457
1   3.127901 -3.220247  2.586667  2.487901
2   0.739753 -0.097778  1.228889  1.174321
3   0.645926  1.560988  2.141728  2.196790
4   2.698519  2.216296  2.607901  2.562963
..       ...       ...       ...       ...
77  0.958765  0.360988  1.488148  1.226173
78 -0.180247  0.092346  0.356790 -0.061728
79 -0.381728  0.849383  1.809136  1.217037
80  2.520988  3.422222  3.548519  3.673333
81  0.177284 -1.751358  0.345432 -0.013333

[82 rows x 4 columns]

In [59]:
df_04 = pd.DataFrame()
endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==4:
        endData.append(homaList_01[4][i]-homaList_01[3][i])
        
df_04['homa_01'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==4:
        endData.append(homaList_01[4][i]-homaList_01[2][i])
        
df_04['homa_02'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==4:
        endData.append(homaList_01[4][i]-homaList_01[1][i])
        
df_04['homa_03'] = endData

print(df_04)

     homa_01   homa_02   homa_03
0   0.486049  0.976049  0.980741
1   2.662222  0.326667  2.268148
2   1.305926  0.985432  1.883210
3   0.369136 -2.684444 -1.369877
4   0.721111  1.441111  1.444444
..       ...       ...       ...
58  0.357531  0.014568  1.188148
59  1.420741  1.421235  1.425679
60 -0.448889 -0.216914  0.016049
61  1.429877  2.504691  3.258765
62 -0.079506  0.468642 -0.274074

[63 rows x 3 columns]

In [60]:
df_05 = pd.DataFrame()
endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==3:
        endData.append(homaList_01[3][i]-homaList_01[2][i])
        
df_05['homa_01'] = endData

endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==3:
        endData.append(homaList_01[3][i]-homaList_01[1][i])
        
df_05['homa_02'] = endData

print(df_05)

     homa_01    homa_02
0  -0.226914   0.175062
1  -0.740741  -0.740247
2  -0.088642  -0.179753
3   0.533333  -0.097284
4  -0.364938  -0.567901
5   1.660741  -0.531605
6   0.245309   0.489877
7   0.744691   1.493827
8   0.378889   0.755556
9   0.664444   1.334321
10 -0.005679  -0.309383
11  0.278025   0.546914
12  2.225185   1.907654
13 -3.098519  -1.126914
14  0.374074   0.309383
15 -1.654815  -0.579506
16 -0.297037   1.187654
17  1.426667   2.850864
18 -0.157778   0.679012
19 -0.801975  -1.573580
20 -0.124074  -0.251852
21  0.289506   0.575556
22  0.239630   0.476296
23 -0.370370 -13.296543
24 -0.015309   1.231358
25 -1.257531  -1.456049
26  2.296296   1.441975
27  1.198025  -0.240000
28 -1.121481  -0.031358
29 -1.809383  -1.598025
30  0.925556   1.858765
31 -3.148148  -1.516543
32 -0.031111   1.017778
33  2.863210   2.823704
34  0.150000   0.309877
35 -0.706420  -6.232346
36 -0.538272   0.374321
37  0.865185  -0.112593
38 -0.468642   0.123210
39  1.389877   2.112840
40  0.373951   0.751111
41 -1.918765   0.487654
42 -1.477778  -1.997778
43  0.025926   1.991605
44  0.892346   1.253086
45  0.262222   0.258272
46  0.602222   1.209136
47  0.916543   2.085185
48 -0.304691  -0.062963
49  0.121481   0.192593
50 -0.408642  -0.780247
51  2.215309   2.760988
52 -0.241728   0.468148
53  0.039506   0.009877
54  3.604938   5.157531
55  1.603210  -0.007407
56 -0.998272  -0.814815
57 -2.638025  -0.809877

In [61]:
df_06 = pd.DataFrame()
endData = []
for i in range(len(homaList_01)):
    if data_01["phase"][i]==2:
        endData.append(homaList_01[2][i]-homaList_01[1][i])
        
df_06['homa_01'] = endData

print(df_06)

     homa_01
0   1.398519
1   0.620741
2   1.323704
3   0.268395
4  -0.000617
5  -1.108889
6  -0.229012
7   0.097654
8   0.331111
9   1.222840
10 -0.594815
11  1.108642
12  0.956667
13  1.030123
14 -0.698272
15 -0.502716
16 -0.726667
17  2.328889
18  1.366914
19  1.034691
20  0.517531
21  2.403951
22  1.609877
23 -0.311852
24  0.593333
25  1.217531
26  3.334321
27  1.825185
28  0.714568
29  0.852222
30 -0.489383
31  6.133827
32  1.123457
33  0.428889
34  1.964938
35 -2.850370
36 -0.127037
37  0.879877
38 -0.177407

In [62]:
df_total = pd.concat([df_01,df_02,df_03,df_04,df_05,df_06], axis=1)

In [63]:
df_total

,homa_01,homa_02,homa_03,homa_04,homa_05,homa_06,homa_01,homa_02,homa_03,homa_04,...,homa_01,homa_02,homa_03,homa_04,homa_01,homa_02,homa_03,homa_01,homa_02,homa_01
0,0.047407,-0.020494,-1.089630,1.526420,-0.565432,0.131358,-1.067654,-0.810370,0.004198,-1.065185,...,-0.235062,0.677531,1.598272,0.303457,0.486049,0.976049,0.980741,-0.226914,0.175062,1.398519
1,-0.570864,-1.299259,-0.179753,-0.167407,0.338025,0.746667,1.408395,2.854321,1.976296,1.768889,...,3.127901,-3.220247,2.586667,2.487901,2.662222,0.326667,2.268148,-0.740741,-0.740247,0.620741
2,0.740741,-0.194568,0.014074,-1.282963,0.235309,0.220988,-1.061975,0.658519,-1.012099,0.043457,...,0.739753,-0.097778,1.228889,1.174321,1.305926,0.985432,1.883210,-0.088642,-0.179753,1.323704
3,0.605432,0.143951,0.537778,-0.126420,0.678519,0.079012,6.246667,6.540741,7.847901,7.864198,...,0.645926,1.560988,2.141728,2.196790,0.369136,-2.684444,-1.369877,0.533333,-0.097284,0.268395
4,0.146667,-1.063210,-0.099259,-0.897037,-0.635556,0.374074,-0.111605,-0.245432,-2.147654,0.345185,...,2.698519,2.216296,2.607901,2.562963,0.721111,1.441111,1.444444,-0.364938,-0.567901,-0.000617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.958765,0.360988,1.488148,1.226173,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.180247,0.092346,0.356790,-0.061728,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.381728,0.849383,1.809136,1.217037,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.520988,3.422222,3.548519,3.673333,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.177284,-1.751358,0.345432,-0.013333,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df_total.to_excel('/home/ekim_reverse/study/Python.study/diff_homa.xlsx')

In [ ]:
endData = []
for i in range(len(gluList)):
    if data["phase"][i]==7:
        endData.append(gluList[7][i]-gluList[4][i])
        
df['glu_03'] = endData
print(df)

In [56]:
len(endData)

2726

In [39]:
gluList[7][1]-gluList[6][1]

22

In [42]:
gluList.head(8)

       1    2    3    4    5    6    7
0  104.0  113  121  140  109  105  114
1   83.0   99  104  108   83   90  112
2   82.0  138  100   91   96  111  118
3   82.0   89  100   99  104   98  123
4   89.0  103  115  132  123  126  136
5   96.0  106  107  111  115  121  108
6   82.0   99  102  104  102   97  107
7   84.0   95  100   94  107  102  131

In [43]:
gluList[7][1]

112

In [49]:
data["phase"][1]==3

True

In [52]:
data["phase"].head()

0    4
1    3
2    2
3    6
4    4
Name: phase, dtype: int64

In [50]:
data["phase"][1]

3