In [39]:
import pandas as pd
import numpy as np

In [40]:
# data = pd.read_excel('/home/ekim_reverse/study/Python.study/DATA_20191210_prep4.xlsx', sheet_name="filtered")

In [42]:
data_01 = pd.read_excel('/home/ekim_reverse/PyCode/study/DATA_20191210_prep4_1.xlsx', sheet_name="Sheet1")

In [43]:
data_01.head()

,RID,SEX,phase,AS1_GLU,AS2_GLU,AS3_GLU,AS4_GLU,AS5_GLU,AS6_GLU,AS7_GLU,...,AS6_HBA1C,AS7_HBA1C,AS1_HOMA,AS2_HOMA,AS3_HOMA,AS4_HOMA,AS5_HOMA,AS6_HOMA,AS7_HOMA,DM
0,EPI18_079_000033,1,4,104,113,121,140,109,105,114,...,5.9,6.0,1.335309,1.340000,1.830000,2.316049,1.399506,1.659259,2.082963,1
1,EPI18_079_000051,2,3,83,99,104,108,83,90,112,...,5.3,5.7,1.578025,1.980000,1.753086,4.080000,1.598519,1.866667,3.899259,1
2,EPI18_079_000069,1,2,82,138,100,91,96,111,118,...,5.6,5.9,2.247407,3.645926,2.469136,1.954815,1.991111,1.836296,2.097778,1
3,EPI18_079_000075,2,6,82,89,100,99,104,98,123,...,6.7,6.1,0.749136,3.823704,2.754321,3.568889,3.826173,2.758519,5.557778,1
4,EPI18_079_000126,2,4,89,103,115,132,123,126,136,...,6.7,7.1,1.186667,3.128148,0.792593,3.454815,2.551111,2.022222,2.720000,1

In [ ]:
# gluList = data.loc[:,"AS1_GLU":"AS7_GLU"]
# altList = data.loc[:,"AS1_ALT":"AS7_ALT"]
# tgList = data.loc[:,"AS1_TG":"AS7_TG"]
# waistList = data.loc[:,"AS1_WAIST":"AS7_WAIST"]
# fib4List = data.loc[:,"AS1_FIB4":"AS7_FIB4"]
# hba1cList = data.loc[:,"AS1_HBA1C":"AS7_HBA1C"]
# homaList = data.loc[:,"AS1_HOMA":"AS7_HOMA"]

In [ ]:
# gluList

In [ ]:
# df=pd.DataFrame()

In [ ]:
# data["phase"][0]

In [ ]:
# gluList.columns = [1,2,3,4,5,6,7]
# altList.columns = [1,2,3,4,5,6,7]
# tgList.columns = [1,2,3,4,5,6,7]
# waistList.columns = [1,2,3,4,5,6,7]
# fib4List.columns = [1,2,3,4,5,6,7]
# hba1cList.columns = [1,2,3,4,5,6,7]
# homaList.columns = [1,2,3,4,5,6,7]

In [44]:
gluList_01 = data_01.loc[:,"AS1_GLU":"AS7_GLU"]
altList_01 = data_01.loc[:,"AS1_ALT":"AS7_ALT"]
tgList_01 = data_01.loc[:,"AS1_TG":"AS7_TG"]
waistList_01 = data_01.loc[:,"AS1_WAIST":"AS7_WAIST"]
fib4List_01 = data_01.loc[:,"AS1_FIB4":"AS7_FIB4"]
hba1cList_01 = data_01.loc[:,"AS1_HBA1C":"AS7_HBA1C"]
homaList_01 = data_01.loc[:,"AS1_HOMA":"AS7_HOMA"]
astList_01 = data_01.loc[:,"AS1_AST":"AS7_AST"]
tchlList_01 = data_01.loc[:,"AS1_TCHL":"AS7_TCHL_N"]
hsiList_01 = data_01.loc[:,"AS1_HSI":"AS7_HSI"]

In [45]:
# endData = []
# for i in range(len(gluList)):
#     for j in range(len(gluList.columns)):
#         if data["phase"][i]==gluList.columns[j]:
#             endData.append(gluList[j+1][i]-gluList[j][i])
# df['glu_01'] = endData
# print(df)

In [46]:
altList_01

     AS1_ALT  AS2_ALT  AS3_ALT  AS4_ALT  AS5_ALT  AS6_ALT  AS7_ALT
0         83       56       63       32       26       54       89
1         16       13       17       13       14       15       13
2         30       33       31       16       14       18       24
3         15       24       20       27       38       21       45
4         19       24       26       24       21       18       20
..       ...      ...      ...      ...      ...      ...      ...
367       38       19       41       37       23       40       40
368       19       28       25       18       24       25       16
369       19       16       19       12       15       17       10
370       33       18       26       18       36       45       35
371       69       93       81       58       52       22       27

[372 rows x 7 columns]

In [47]:
gluList_01.columns = [1,2,3,4,5,6,7]
altList_01.columns = [1,2,3,4,5,6,7]
tgList_01.columns = [1,2,3,4,5,6,7]
waistList_01.columns = [1,2,3,4,5,6,7]
fib4List_01.columns = [1,2,3,4,5,6,7]
hba1cList_01.columns = [1,2,3,4,5,6,7]
homaList_01.columns = [1,2,3,4,5,6,7]
astList_01.columns = [1,2,3,4,5,6,7]
tchlList_01.columns = [1,2,3,4,5,6,7]
hsiList_01.columns = [1,2,3,4,5,6,7]

In [66]:
df_01=pd.DataFrame()

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==7:
        endData.append(tchlList_01[7][i]-tchlList_01[6][i])
        
df_01['tchl_01'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==7:
        endData.append(tchlList_01[7][i]-tchlList_01[5][i])
        
df_01['tchl_02'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==7:
        endData.append(tchlList_01[7][i]-tchlList_01[4][i])
        
df_01['tchl_03'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==7:
        endData.append(tchlList_01[7][i]-tchlList_01[3][i])
        
df_01['tchl_04'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==7:
        endData.append(tchlList_01[7][i]-tchlList_01[2][i])
        
df_01['tchl_05'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==7:
        endData.append(tchlList_01[7][i]-tchlList_01[1][i])
        
df_01['tchl_06'] = endData

print(df_01)

    tchl_01  tchl_02  tchl_03  tchl_04  tchl_05  tchl_06
0        34       14        8       23        9        5
1        22       28       -3        6        2      -29
2       -26      -35      -19       -7      -33      -19
3        12       22        3       34       30      -25
4       -59      -93      -51      -74      -70      -54
5        55       21       28       20       24       64
6       -76      -84      -24      -77      -47      -89
7         5       -9      -18       19       -1       -9
8       -48      -38      -88      -56      -61      -53
9       -10       15       10       36       31       48
10       -8        1      -37      -20       -3        3
11      -43      -68      -67       13       10      -20
12      -89      -42     -200     -108      -59      -82
13        4       -2       -6       17       28       -3
14      -34       14       -9       50      -12       20
15      -56      -27      -50       14      -39      -36
16       41       58       61       70       12      -15
17       19       50       40       52       62       92
18      -76      -99      -88     -108      -77      -52
19      -19      -36      -37      -17      -84       20
20        7       22       37       72       81       60
21      -12       14       11        7       25       -2
22      -44      -43     -102      -39     -129     -134
23        4       16       16        3       18       -1
24      -34      -13      -11       -1       -8       23
25       -1      -13       -1       -2      -37       -1
26      -14       26      -49      -67      -97      -45
27       29       84       84       88       99       46
28      -14      -15      -19      -15      -11      -11
29      -16       25       42       38       14       46
30       20       17      -35      -47      -29      -33
31       68      -33      -18        8       -1      -16
32      -19        4       -5      -31      -79      -36
33      -71      -73     -116      -17      -66      -39
34      -35      -70     -119      -68      -52      -80
35      -92      -45      -75      -63      -97      -69
36      -30      -46      -44      -79      -26      -18
37       27      -47      -49      -24      -14      -10
38       28       41      -61      -43       38      -67
39       18       20       -8      -20      -30       24
40      -18       23       12      -10       -5        0
41       11        1       13       21       12       14
42       -9      -23       -2        9       -5      -18
43       24       19      -76      -45      -63      -51
44       11       -6       -4      -51      -39      -60
45       11      -17      -20        7      -14        2
46      -53      -28        3      -27      -40       -7
47      -16      -62      -90      -45      -29      -69
48      -36        0      -43      -48      -69      -27
49        7      -19       14       20        5       11
50       -4       26       11       31       21       14
51       29       21       -7       37       16        8
52      -27      -19       -9      -33      -27      -25
53       40       21        8       53       41       73
54      -53      -95      -48      -61      -81      -57
55       10        5        7      -86      -46      -33
56       -4      -30       -8      -11       11      -33

In [67]:
df_02 = pd.DataFrame()
endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==6:
        endData.append(tchlList_01[6][i]-tchlList_01[5][i])
        
df_02['tchl_01'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==6:
        endData.append(tchlList_01[6][i]-tchlList_01[4][i])
        
df_02['tchl_02'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==6:
        endData.append(tchlList_01[6][i]-tchlList_01[3][i])
        
df_02['tchl_03'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==6:
        endData.append(tchlList_01[6][i]-tchlList_01[2][i])
        
df_02['tchl_04'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==6:
        endData.append(tchlList_01[6][i]-tchlList_01[1][i])
        
df_02['tchl_05'] = endData

print(df_02)

    tchl_01  tchl_02  tchl_03  tchl_04  tchl_05
0       -22       19       24       -1       91
1         0       -5      -10       15        0
2        -5      -66      -46      -17        4
3        22        4       41       15       12
4        44       39       66       72       28
..      ...      ...      ...      ...      ...
68      -14       68       35       22       40
69        4       38       52       39       41
70      -57      -47      -28      -14      -32
71        4       37       41        5       50
72      -17       30      -31      -18        3

[73 rows x 5 columns]

In [68]:
df_03 = pd.DataFrame()
endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==5:
        endData.append(tchlList_01[5][i]-tchlList_01[4][i])
        
df_03['tchl_01'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==5:
        endData.append(tchlList_01[5][i]-tchlList_01[3][i])
        
df_03['tchl_02'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==5:
        endData.append(tchlList_01[5][i]-tchlList_01[2][i])
        
df_03['tchl_03'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==5:
        endData.append(tchlList_01[5][i]-tchlList_01[1][i])
        
df_03['tchl_04'] = endData

print(df_03)

    tchl_01  tchl_02  tchl_03  tchl_04
0        19        6       18      -17
1        11      -25       -4       30
2       -71      -34       -7      -28
3        42       52       45       66
4       -12        6       -4      -18
..      ...      ...      ...      ...
77       71       62      113       91
78      -10       30       70       57
79       42       36       13       60
80       25       84       43       53
81       21       13        7      -17

[82 rows x 4 columns]

In [69]:
df_04 = pd.DataFrame()
endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==4:
        endData.append(tchlList_01[4][i]-tchlList_01[3][i])
        
df_04['tchl_01'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==4:
        endData.append(tchlList_01[4][i]-tchlList_01[2][i])
        
df_04['tchl_02'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==4:
        endData.append(tchlList_01[4][i]-tchlList_01[1][i])
        
df_04['tchl_03'] = endData

print(df_04)

    tchl_01  tchl_02  tchl_03
0        12       31       11
1        36       22       10
2        33       38       32
3         8       21        8
4        11      -12       11
..      ...      ...      ...
58       22       50       67
59       17       -1       34
60       -6       -1       16
61       33       17       16
62       20       -4       -8

[63 rows x 3 columns]

In [70]:
df_05 = pd.DataFrame()
endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==3:
        endData.append(tchlList_01[3][i]-tchlList_01[2][i])
        
df_05['tchl_01'] = endData

endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==3:
        endData.append(tchlList_01[3][i]-tchlList_01[1][i])
        
df_05['tchl_02'] = endData

print(df_05)

    tchl_01  tchl_02
0        -9      -10
1         9        0
2        42      -52
3       -19      -23
4        10       -3
5       -25       13
6        16        7
7        18       18
8       -19      -11
9        16       29
10      -44      -33
11      -12        7
12      -32      -25
13       22       20
14       28        6
15      -15        4
16      -45       -6
17       22       26
18       25       27
19       21       32
20      -12      -41
21      -37      -20
22       41       81
23      -18       32
24       19       -3
25      -42       16
26       14       14
27      -21       21
28       31       33
29       22        0
30       40       55
31        4      -19
32       -2       46
33      -48      -32
34      -27       13
35       -2       37
36      -51      -30
37       85       56
38       18        3
39       -4      -31
40     -102      -10
41       -2        5
42      -47      -36
43       12       -6
44       -3       14
45       20       50
46      -26       -7
47        5      -13
48      -10       28
49       17       28
50        4      -11
51        2       -2
52      -64      -43
53      -32        8
54        9      -14
55       14       -9
56       32       16
57      -56      -24

In [71]:
df_06 = pd.DataFrame()
endData = []
for i in range(len(tchlList_01)):
    if data_01["phase"][i]==2:
        endData.append(tchlList_01[2][i]-tchlList_01[1][i])
        
df_06['tchl_01'] = endData

print(df_06)

    tchl_01
0        50
1        12
2        30
3       -32
4        47
5        -6
6        30
7        10
8       -17
9        38
10       58
11        5
12      -29
13      -20
14       36
15       -8
16       25
17       87
18       18
19       -8
20       33
21       64
22      -67
23       30
24      -22
25       -7
26       97
27       -7
28      -19
29       35
30      -14
31      -99
32       -1
33       -2
34       14
35      -18
36       13
37        4
38       22

In [72]:
df_total = pd.concat([df_01,df_02,df_03,df_04,df_05,df_06], axis=1)

In [73]:
df_total

,tchl_01,tchl_02,tchl_03,tchl_04,tchl_05,tchl_06,tchl_01,tchl_02,tchl_03,tchl_04,...,tchl_01,tchl_02,tchl_03,tchl_04,tchl_01,tchl_02,tchl_03,tchl_01,tchl_02,tchl_01
0,34.0,14.0,8.0,23.0,9.0,5.0,-22.0,19.0,24.0,-1.0,...,19,6,18,-17,12.0,31.0,11.0,-9.0,-10.0,50.0
1,22.0,28.0,-3.0,6.0,2.0,-29.0,0.0,-5.0,-10.0,15.0,...,11,-25,-4,30,36.0,22.0,10.0,9.0,0.0,12.0
2,-26.0,-35.0,-19.0,-7.0,-33.0,-19.0,-5.0,-66.0,-46.0,-17.0,...,-71,-34,-7,-28,33.0,38.0,32.0,42.0,-52.0,30.0
3,12.0,22.0,3.0,34.0,30.0,-25.0,22.0,4.0,41.0,15.0,...,42,52,45,66,8.0,21.0,8.0,-19.0,-23.0,-32.0
4,-59.0,-93.0,-51.0,-74.0,-70.0,-54.0,44.0,39.0,66.0,72.0,...,-12,6,-4,-18,11.0,-12.0,11.0,10.0,-3.0,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71,62,113,91,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-10,30,70,57,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42,36,13,60,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25,84,43,53,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21,13,7,-17,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
#df_total.to_excel('/home/ekim_reverse/PyCode/study/diff_tchl.xlsx')

In [ ]:
# df.loc(len(df)+1) =newdata

In [ ]:
endData = []
for i in range(len(gluList)):
    if data["phase"][i]==7:
        endData.append(gluList[7][i]-gluList[4][i])
        
df['glu_03'] = endData
print(df)

In [ ]:
len(endData)

In [ ]:
gluList[7][1]-gluList[6][1]

In [ ]:
gluList.head(8)

In [ ]:
gluList[7][1]

In [ ]:
data["phase"][1]==3

In [ ]:
data["phase"].head()

In [ ]:
data["phase"][1]